"""
scheduler/launchers/gcp_launcher.py
────────────────────────────────────
GCP Compute Engine Spot VM launcher.

Creates a preemptible/spot VM, injects startup script via metadata,
attaches service account, updates job_state.json on S3, and returns
instance metadata for checkpoint resume.

Changes from previous version:
    - Instance metadata now includes AWS creds + CHECKPOINT_S3_BUCKET
      so the startup script can authenticate to S3 for trainer file
      downloads and checkpoint reads/writes.
    - _update_job_state() writes to S3 instead of local disk.
    - GCS bucket retained only for optional .pt file storage.

Required env vars:
    GCP_PROJECT_ID
    GCP_ZONE                    (default: us-central1-a)
    GCP_SERVICE_ACCOUNT_EMAIL   (SA email for the VM identity)
    CHECKPOINT_S3_BUCKET        (S3 bucket — single source of truth)
    CHECKPOINT_GCS_BUCKET       (GCS bucket — GCP .pt storage only, optional)
    AWS_ACCESS_KEY_ID           (injected into VM metadata for S3 access)
    AWS_SECRET_ACCESS_KEY
    AWS_REGION
    GOOGLE_APPLICATION_CREDENTIALS (path to SA JSON key)
"""

import os
import json
import logging
import time
from datetime import datetime, timezone

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

GCP_PROJECT  = os.getenv("GCP_PROJECT_ID",           "")
GCP_ZONE     = os.getenv("GCP_ZONE",                 "us-central1-a")
GCP_SA_EMAIL = os.getenv("GCP_SERVICE_ACCOUNT_EMAIL", "")
GCS_BUCKET   = os.getenv("CHECKPOINT_GCS_BUCKET",    "")
S3_BUCKET    = os.getenv("CHECKPOINT_S3_BUCKET",     "")


def _get_compute_client():
    """Build GCP Compute Engine API client via google-api-python-client."""
    try:
        import googleapiclient.discovery
        return googleapiclient.discovery.build("compute", "v1")
    except ImportError:
        logger.error("[GCP Launcher] google-api-python-client not installed. "
                     "Run: pip install google-api-python-client google-auth")
        raise
    except Exception as e:
        logger.error(f"[GCP Launcher] Failed to build Compute client: {e}")
        raise


def _s3_client():
    return boto3.client(
        "s3",
        aws_access_key_id     = os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key = os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name           = os.getenv("AWS_REGION", "us-east-1"),
    )


def _s3_put_json(key: str, data: dict) -> bool:
    if not S3_BUCKET:
        logger.warning(f"[GCP Launcher] S3_BUCKET not set — skipping S3 write for {key}")
        return False
    try:
        _s3_client().put_object(
            Bucket      = S3_BUCKET,
            Key         = key,
            Body        = json.dumps(data, indent=2).encode(),
            ContentType = "application/json",
        )
        return True
    except Exception as e:
        logger.warning(f"[GCP Launcher] S3 put failed for {key}: {e}")
        return False


def _s3_get_json(key: str) -> dict:
    if not S3_BUCKET:
        return {}
    try:
        obj = _s3_client().get_object(Bucket=S3_BUCKET, Key=key)
        return json.loads(obj["Body"].read())
    except ClientError as e:
        if e.response["Error"]["Code"] in ("NoSuchKey", "404"):
            return {}
        logger.warning(f"[GCP Launcher] S3 get failed for {key}: {e}")
        return {}
    except Exception as e:
        logger.warning(f"[GCP Launcher] S3 get failed for {key}: {e}")
        return {}


def create_gcp_vm(decision: dict, startup_script: str) -> dict:
    """
    Launch a GCP Spot VM based on the selector decision.

    Args:
        decision:       dict from selector.pick_best_cloud()
        startup_script: bash script (generated by launcher._build_training_script)

    Returns:
        dict with instance_name, instance_id, zone, internal_ip,
             status, s3_bucket, cloud
    """
    job_id        = decision.get("job_id",        f"job-{int(time.time())}")
    instance_type = decision["instance_type"]
    zone          = decision.get("zone", GCP_ZONE)
    project       = GCP_PROJECT

    if not project:
        raise EnvironmentError("GCP_PROJECT_ID env var not set")

    instance_name = f"ml-job-{job_id}-{int(time.time())}"[:63]

    logger.info(f"[GCP Launcher] Creating Spot VM: {instance_name} "
                f"({instance_type}) in {zone}")

    machine_type_url = f"zones/{zone}/machineTypes/{instance_type}"

    # GPU instances (a2, g2, n1+accelerator) require onHostMaintenance=TERMINATE.
    # CPU-only instances (e2, n1 without accelerator) can use MIGRATE on-demand.
    has_gpu = (
        instance_type.startswith("a2") or
        instance_type.startswith("g2") or
        decision.get("gpu_count", 0) > 0
    )

    on_demand = decision.get("spot") is False or os.getenv("_GCP_FORCE_ONDEMAND") == "1"

    if on_demand:
        if has_gpu:
            scheduling = {
                "onHostMaintenance": "TERMINATE",
                "automaticRestart":  False,
            }
        else:
            scheduling = {
                "onHostMaintenance": "MIGRATE",
                "automaticRestart":  True,
            }
    else:
        scheduling = {
            "provisioningModel":         "SPOT",
            "instanceTerminationAction": "STOP",
            "onHostMaintenance":         "TERMINATE",
            "automaticRestart":          False,
        }

    # GPU accelerators (if instance needs them separately from A2)
    accelerators = []
    gpu_count = decision.get("gpu_count", 0)
    gpu_model = decision.get("gpu_model")
    if gpu_count > 0 and gpu_model and not instance_type.startswith("a2"):
        accel_map = {
            "T4":   "nvidia-tesla-t4",
            "V100": "nvidia-tesla-v100",
            "K80":  "nvidia-tesla-k80",
        }
        accel_type = accel_map.get(gpu_model, "nvidia-tesla-t4")
        accelerators = [{
            "acceleratorCount": gpu_count,
            "acceleratorType":  f"zones/{zone}/acceleratorTypes/{accel_type}",
        }]

    service_accounts = []
    if GCP_SA_EMAIL:
        service_accounts = [{
            "email":  GCP_SA_EMAIL,
            "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/devstorage.read_write",
            ],
        }]

    instance_body = {
        "name":        instance_name,
        "machineType": machine_type_url,
        "scheduling":  scheduling,
        "disks": [{
            "boot":             True,
            "autoDelete":       True,
            "initializeParams": {
                # pytorch-latest-gpu was retired from deeplearning-platform-release.
                # Use Ubuntu 22.04 LTS — startup script installs torch via pip at boot.
                "sourceImage": os.getenv(
                    "GCP_BOOT_IMAGE",
                    "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
                ),
                "diskSizeGb":  "100",
                "diskType":    f"zones/{zone}/diskTypes/pd-ssd",
            },
        }],
        "networkInterfaces": [{
            "network": "global/networks/default",
            "accessConfigs": [{
                "type": "ONE_TO_ONE_NAT",
                "name": "External NAT",
            }],
        }],
        "metadata": {
            "items": [
                # Script to run at boot (auto-detects cloud inside)
                {"key": "startup-script",        "value": startup_script},
                # Job identity
                {"key": "job-id",                "value": job_id},
                # S3 — single source of truth for all JSON + checkpoints
                # These are curled by the startup script from the metadata server
                {"key": "CHECKPOINT_S3_BUCKET",  "value": S3_BUCKET},
                {"key": "AWS_ACCESS_KEY_ID",     "value": os.getenv("AWS_ACCESS_KEY_ID",     "")},
                {"key": "AWS_SECRET_ACCESS_KEY", "value": os.getenv("AWS_SECRET_ACCESS_KEY", "")},
                {"key": "AWS_DEFAULT_REGION",    "value": os.getenv("AWS_REGION", "us-east-1")},
                # GCS — kept for optional .pt file storage on GCP only
                {"key": "CHECKPOINT_GCS_BUCKET", "value": GCS_BUCKET},
            ]
        },
        "serviceAccounts": service_accounts,
        "tags": {"items": ["ml-training", "spot-vm"]},
    }

    if accelerators:
        instance_body["guestAccelerators"] = accelerators

    try:
        compute = _get_compute_client()
        op = compute.instances().insert(
            project=project,
            zone=zone,
            body=instance_body,
        ).execute()

        logger.info(f"[GCP Launcher] Insert operation started: {op.get('name')}")
        _wait_for_operation(compute, project, zone, op["name"])

        instance = compute.instances().get(
            project=project,
            zone=zone,
            instance=instance_name,
        ).execute()

        internal_ip = (
            instance.get("networkInterfaces", [{}])[0]
                    .get("networkIP", "unknown")
        )
        instance_id = str(instance.get("id", ""))

        logger.info(f"[GCP Launcher] ✓ VM ready: {instance_name}  IP={internal_ip}")

    except Exception as e:
        err_str = str(e)
        if "free tier" in err_str.lower() or "free-tier" in err_str.lower():
            raise RuntimeError(
                f"[GCP] Free-tier billing account cannot launch GPU instances "
                f"({instance_type}). Options:\n"
                f"  1. Upgrade billing: https://cloud.google.com/free/docs/gcp-free-tier#how-to-upgrade\n"
                f"  2. Use CPU instances: set GCP_ENABLE_GPU=false (already the default)\n"
                f"  Original error: {e}"
            ) from e
        if "quota" in err_str.lower():
            raise RuntimeError(
                f"[GCP] GPU quota exceeded for {instance_type} in {zone}. "
                f"Request quota increase: https://cloud.google.com/compute/quotas\n"
                f"Original error: {e}"
            ) from e
        logger.error(f"[GCP Launcher] VM creation failed: {e}")
        raise

    result = {
        "cloud":         "gcp",
        "instance_name": instance_name,
        "instance_id":   instance_id,
        "instance_type": instance_type,
        "zone":          zone,
        "internal_ip":   internal_ip,
        "status":        "RUNNING",
        "s3_bucket":     S3_BUCKET,
        "launched_at":   datetime.now(timezone.utc).isoformat(),
    }

    _update_job_state(job_id, result)
    return result


def _wait_for_operation(compute, project: str, zone: str, op_name: str,
                         timeout: int = 120):
    """Poll zone operation until done or timeout."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        op = compute.zoneOperations().get(
            project=project, zone=zone, operation=op_name
        ).execute()
        if op.get("status") == "DONE":
            if "error" in op:
                raise RuntimeError(f"GCP operation error: {op['error']}")
            return
        time.sleep(5)
    raise TimeoutError(f"GCP operation {op_name} timed out after {timeout}s")


def _update_job_state(job_id: str, launch_result: dict):
    """Merge launch_result into job_state.json on S3."""
    key      = f"checkpoints/{job_id}/job_state.json"
    existing = _s3_get_json(key)
    existing.update({
        "launch_result": launch_result,
        "updated_at":    datetime.now(timezone.utc).isoformat(),
    })
    if _s3_put_json(key, existing):
        logger.info(f"[GCP Launcher] job_state.json updated on S3 for {job_id}")
    else:
        logger.warning(f"[GCP Launcher] Could not update job_state.json on S3 for {job_id}")